version: '2'
volumes:
    odoodata:
    pgdata:
services:
  odoo:
    build: ./odoo
    ports:
      - 8069:8069
      - 8072:8072
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    volumes:
      - "odoodata:/opt/odoo/data"
      # mount volumes for dev needs
      - "./odoo/extras:/opt/odoo/extras"
    # launch container in odoo dev mode
    # command: run --dev
  postgres:
    image: postgres:11.0
    # to access pg from outside
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "pgdata:/var/lib/postgresql/data"
